FROM node:20.14.0-alpine3.20 AS base

FROM base AS builder
WORKDIR /app
ARG VITE_API_URL=http://localhost:8000
ENV VITE_API_URL=${VITE_API_URL}
COPY package*.json /app
RUN npm install
COPY . ./
RUN npm run build:admin

FROM nginx:1.27
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist-admin /usr/share/nginx/html
EXPOSE 80
